FROM golang:1.25-alpine
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 go build -o mtp ./cmd/main.go

FROM alpine:latest
COPY --from=builder /app/mtp /usr/local/bin/mtp
ENTRYPOINT ["mtp"]